/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApplicationGroup } from './application-group';
/**
 * 
 * @export
 * @interface ApplicationUser
 */
export interface ApplicationUser {
    /**
     * 
     * @type {string}
     * @memberof ApplicationUser
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationUser
     */
    refreshToken?: string;
    /**
     * 
     * @type {number}
     * @memberof ApplicationUser
     */
    groupId: number;
    /**
     * 
     * @type {ApplicationGroup}
     * @memberof ApplicationUser
     */
    group?: ApplicationGroup;
}
