/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { QueryHandoverResponse } from './query-handover-response';
/**
 * 
 * @export
 * @interface GridQueryResponseOfQueryHandoverResponse
 */
export interface GridQueryResponseOfQueryHandoverResponse {
    /**
     * 
     * @type {number}
     * @memberof GridQueryResponseOfQueryHandoverResponse
     */
    totalRows: number;
    /**
     * 
     * @type {Array<QueryHandoverResponse>}
     * @memberof GridQueryResponseOfQueryHandoverResponse
     */
    rows?: Array<QueryHandoverResponse>;
}
