/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface HandoverLog
 */
export interface HandoverLog {
    /**
     * 
     * @type {string}
     * @memberof HandoverLog
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof HandoverLog
     */
    logTime: Date;
    /**
     * 
     * @type {string}
     * @memberof HandoverLog
     */
    logText?: string;
    /**
     * 
     * @type {string}
     * @memberof HandoverLog
     */
    logBy?: string;
    /**
     * 
     * @type {string}
     * @memberof HandoverLog
     */
    handoverId: string;
}
