/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface IPerson
 */
export interface IPerson {
    /**
     * 
     * @type {string}
     * @memberof IPerson
     */
    sAMAccountName?: string;
    /**
     * 
     * @type {string}
     * @memberof IPerson
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof IPerson
     */
    mail?: string;
    /**
     * 
     * @type {string}
     * @memberof IPerson
     */
    password?: string;
}
