/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GetWardPatient } from './get-ward-patient';
/**
 * 
 * @export
 * @interface QueryHandoverResponse
 */
export interface QueryHandoverResponse extends GetWardPatient {
    /**
     * 
     * @type {number}
     * @memberof QueryHandoverResponse
     */
    groupId?: number;
    /**
     * 
     * @type {string}
     * @memberof QueryHandoverResponse
     */
    groupName?: string;
}
