# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  clinicalhandoverwebapi:
    image: clinicalhandoverwebapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"

    environment:
      SA_PASSWORD: "XXX"
      ACCEPT_EULA: "Y"      